name: Jumpstarter Tests

on:
  workflow_dispatch:

jobs:
  qemu:
    name: jmp-qemu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl qemu-system which createrepo-c pip socat wget tree make git
          pip install uv
      
      - name: Download AutoSD 10 Image
        run: |
          wget \
            -O disk.qcow2.xz \
            https://download.autosd.sig.centos.org/AutoSD-10/nightly/sample-images/auto-osbuild-qemu-autosd10-developer-regular-x86_64-2287871404.8f8e3a0e.qcow2.xz
          xz -d disk.qcow2.xz

      - name: Enable KVM group perms
        run: |
          sudo usermod -aG kvm $USER
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Install Jumpstarter
        run: |
          git clone -b qemu-test https://github.com/odra/jumpstarter.git
          make -C jumpstarter/python build
          pip install jumpstarter/python/dist/*.whl
        working-directory: /tmp
      #  run: pip install --extra-index-url https://pkg.jumpstarter.dev/ jumpstarter-all

      - name: Run VM
        run: |
          sudo ls -la /dev/vsock
          echo $PWD
          tree .
          jmp shell --exporter-config jumpstarter/qemu.exporter.yaml < jumpstarter/qemu.cmd.sh
