name: Run Podman Command

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-podman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl
          podman --version

      - name: Run Podman command as sudo
        run: |
          curl -o auto-image-builder.sh "https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/raw/main/auto-image-builder.sh"
          chmod +x auto-image-builder.sh
          sudo ./auto-image-builder.sh build \
          --target qemu \
          --export qcow2 \
          minimal.aib.yml \
          disk.qcow2
