name: Build AutoSD Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-podman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl
          podman --version
      
      - name: Install auto-image-builder.sh
        run: |
          curl -o auto-image-builder.sh "https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/raw/main/auto-image-builder.sh"
          chmod +x auto-image-builder.sh

      - name: Build simple.aib.yml
        run: |
          sudo ./auto-image-builder.sh build \
          --target qemu \
          --export qcow2 \
          simple.aib.yml \
          disk.qcow2
      
      - name: Build complex.aib.yml
        run: |
          sudo ./auto-image-builder.sh build \
          --target qemu \
          --export qcow2 \
          developer.aib.yml \
          disk.qcow2
